#!/bin/sh
# Regenerate sdith_namespace.h from the compiled shared libraries.
#
# liboqs builds the shared SDitH code once, as sdith_common and (if available)
# sdith_common_avx2, so every symbol they define is global in liboqs' library.
# The header maps those names under a prefix; see README.md.
#
#   ./gen_namespace.sh <liboqs-build>
#
# The avx2 library only exists in an x86_64 build, so run this against one or the
# header will be missing its symbols.
set -eu

if [ $# -ne 1 ] || [ ! -d "$1" ]; then
	echo "usage: $0 <liboqs-build>" >&2
	exit 1
fi

objects=$(
	find "$1" \
	-type d -name 'sdith_sdith_common*.dir' \
	-exec find {} -name '*.o' -print \;
)
if [ -z "$objects" ]; then
	echo "$0: no sdith_sdith_common*.dir objects under $1" >&2
	exit 1
fi

symbols=$(
	echo "$objects" |
	tr '\n' '\0' |
	xargs -0 nm -P | # `nm -P` prints "name type value size"
	awk '$2 ~ /^[ABCDGIRSTVW]$/ { print $1 }' | # filter for defined external symbols (caps)
	sed 's/^_//; s/^oqs_sig_private_sdith_ref_//; s/^oqs_sig_private_sdith_avx2_//' | # strip leading underscore and existing liboqs prefixes
	sort -u
)
if [ -z "$symbols" ]; then
	echo "$0: nm reported no defined symbols" >&2
	exit 1
fi

defines=$(
	echo "$symbols" | 
	awk '{ printf "#define %-61s SDITH_NAMESPACE_FOR_LIBOQS(%s)\n", $1, $1 }'
)

cat > "$(dirname "$0")/sdith_namespace.h" <<EOF
#ifndef SDITH_NAMESPACE_H
#define SDITH_NAMESPACE_H

/**
 * Generated by integration/liboqs/gen_namespace.sh. Do not edit by hand.
 *
 * liboqs compiles the shared SDitH sources once and links every scheme variant
 * against that single copy, so these symbols are global in liboqs' own library.
 */

#ifdef APPLY_NAMESPACE

#ifndef concat2
#define _concat2(a, b) a##b
#define concat2(a, b) _concat2(a, b)
#endif
#define SDITH_NAMESPACE_FOR_LIBOQS(s) concat2(APPLY_NAMESPACE, s)

$defines

#endif  // APPLY_NAMESPACE

#endif  // SDITH_NAMESPACE_H
EOF

echo "$symbols" | wc -l | tr -d ' ' | xargs echo "symbols namespaced:" >&2
